Fixed error specs for ruby 1.9.3.
Two specs failed on Travis for 1.9.3

  1) Store::Timestamps Object Timestamps on save
  Failure/Error: @object.save
  TypeError: can't convert nil into String
         <internal:prelude>:10:in `synchronize'
         ./lib/store/store.rb:341:in `save'
         ./lib/store/timestamps.rb:32:in `save'
         ./spec/lib/timestamps_spec.rb:66:in `block (4 levels) in <top (required)>'
  2) Store::Timestamps Object
  Timestamps ignores updated_at if modified before
  Failure/Error: @object.save
  TypeError: can't convert nil into String
          <internal:prelude>:10:in `synchronize'
          ./lib/store/store.rb:341:in `save'
          ./lib/store/timestamps.rb:32:in `save'
          ./spec/lib/timestamps_spec.rb:72:in `block
          (4 levels) in <top (required)>'